### ISSUE TITLE
New Version Changed Things.

### ISSUE THREAD

**Issue by GaryLBaird** [anibalcucco/basecamp-wrapper#34]
The new version seems to have broken the project.  
This works:
Basecamp.establish_connection!('https://basecamp.com', 'login', 'password') 

This does not:
Basecamp::Person.me
or
Basecamp::Person.me.token

My suspicion is that the new version which removed tokens also moved things around.

**Comment by anibalcucco** [comment]
Apparently now using ssl (```https```) is mandatory, notice the the ```Moved Permanently. => https://...``` error message:

```ruby
> Basecamp.establish_connection!('{account}.basecamphq.com', 'login', 'password')
> Basecamp::Person.me
ActiveResource::Redirection: Failed.  Response code = 301.  Response message = Moved Permanently. => https://{account}.basecamphq.com/people/me.xml
```

We're still defaulting to no ssl (https://github.com/anibalcucco/basecamp-wrapper/blob/master/lib/basecamp/base.rb#L6) so you have pass ```true``` for the ```use_ssl``` param:

```ruby
> Basecamp.establish_connection!('{account}.basecamphq.com', 'login', 'password', true)
> Basecamp::Person.me
=> #<Basecamp::Person:0x007ff5a2b19668 @attributes
```

I'll make the change to default to ```true``` (or probably remove/ignore if "no ssl" doesn't work anymore) soon.

**Comment by anibalcucco** [comment]
Now ```use_ssl``` in ```establish_connection!``` defaults to true: https://github.com/anibalcucco/basecamp-wrapper/pull/35
